#+title: MAPAB Cupen

I lördags gick den traditionsenglia futsal cupen av stapeln, detta i form av MAPAB cupen efter
cupens huvudsponsor.

Våra gulsvarta hjältar inledde hela festen genom att vinna över Månsarp med 1-0 i öppningsmatchen efter att Simon Jonsson nickat in
1-0 efter ett välplacerat utkast av en stensäker Mika "Pekka" Wenroth, som var lätt att förväxla med en tegelvägg. MIF dominerade
första matchen med ett högt bolltempo och ett gedigert försvarsspel.

I omgång två stod ett ungt Råslätt för motståndet och även här visade MIF upp ett tryggt bollspel och stabilt försvar. Väl det
fåtal gånger som Råslätt kom till läge stod Casper "Osten" Gyllensvaan rätt placerad.
Vi sätter varandra i bra lägen med fina passningar bra löpningar, så pass bra att till och med våra två yngsta junisar Gustav Lundh och Wille Rosén lyckas
näta ett respektive två mål vilket leder till en stabil 3-0 seger för de gula och svarta.

I den tredje omgången är det dags för det alla har väntat på. Inför fullsatta läktare är det dags för matchen mellan
Mullsjö och Sandhem.
För den ovetande hade det varit lätt att förväxla de båda lagen (om man bortser från matchställen) då Sandhemslaget bestod av
många forna MIF spelare, så som Charlie Gustafsson, Marcus Palm, bröderna Molin och Casper Bolmstad. Det var upplagt för en
hård kamp mellan två fiender sedan urminnes tider.
Tyvärr visades inte detta i spelet på något sätt... det blev en händelsefattig match med dåligt tempo, sena tacklingar och få målchanser,
men det är kanske det man får förvänta sej av två div 6 lag.

I och med två vinster och en oavgjord hamnar Mullsjö på en första plats i grupp A och får möta Norrahammar i semifinal.
Från Mullsjös grupp A gick även Sandem vidare med sina 5 poäng. I grupp B gick Mariebo och Norrahammar vida med 5 poäng vardera.

Semifinalen mellan MIF och Norrahammar blev en jämn historia, tyvärr inleder Norrahammar med att bara efter några sekunder
smälla in 0 - 1 i Ostens bortre stolpe. Men MIF ger inte upp och vaskar fram målchans efter målchans. Norrahammars målvakt får
göra ett flertal bra räddningar. MIF lyckas inte knäcka Norrahammar och matchen slutar 0 - 1, efter en bra försvarsinsats av det rödvita
Norrahammarslaget.

Allt som allo gör de gulsvarta en bra turnering med många ljusa glimtar. Det ska se ska bli spännade att följa utvecklingen av detta unga
MIF.

I den andra semifinalen ställs Sandhem mot Mariebo, där Jönköpingslaget vinner med 3 - 0.

Finalen blir en lätt match för Norrahammar där de vinner med 3 - 1 och även där vinner genom ett bra försvars och målvaktsspel
trots att Mariebo trycker på mot slutet för att komma tillbaka i matchen.

<b>Resultat</b>

<b>Grupp A</b>

Mullsjö: 7 poäng, +7 målskillnad
Sandhem: 5, +1
Månsarp 2: 3, +1
Råslätt: 0, -5

<b>Gruppspel grupp A</b>

Mullsjö - Månsarp 2     1 - 0
Råslätt - Sandhem       1 - 2

Sandhem - Månsarp 2     0 - 0
Råslätt - Mullsjö       0 - 3

Månsarp - Råslätt       2 - 0
Mullsjö - Sandhem       0 - 0

<b>Grupp B</b>

Mariebo: 6 poäng, +2 målskillnad
Norrahammar: 6, +2
Månsarp: 4, -2
Habo: 1, -2

<b>Gruppspel grupp B</b>

Habo - Månsarp      1 - 1
Mariebo - Norrahammar   0 - 2

Månsarp - Mariebo   0 - 3
Norrahammar - Habo  1 - 0

Månsarp - Norrahammar 1 - 0
Habo - Mariebo      1 - 2

<b>Semifinaler</b>

Mullsjö - Norrahammar   0 - 1

Mariebo - Sandhem       3 - 0

<b>Final</b>

Norrahammar - Mariebo   3 - 1
