#+title: MAPAB Cupen

I lördags gick den traditionsenglia futsal cupen av stapeln, detta i form av MAPAB cupen efter
cupens huvudsponsor.

Våra gulsvarta hjältar inledde hela festen genom att vinna över Månsarp med 1-0 i öppningsmatchen efter att Simon Jonsson nickat in
1-0 efter ett välplacerat utkast av en stensäker Mika "Pekka" Wenroth, som var lätt att förväxla med en tegelvägg. MIF dominerade
första matchen med ett högt bolltempo och ett gedigert försvarsspel.

I omgång två stod ett ungt Råslätt för motståndet och även här visade MIF upp ett tryggt bollspel och stabilt försvar. Väl det
fåtal gånger som Råslätt kom till läge stod Casper "Osten" Gyllensvaan rätt placerad.
Vi sätter varandra i bra lägen med fina passningar bra löpningar, så pass bra att till och med våra två yngsta junisar Gustav Lundh och Wille Rosén lyckas
näta ett respektive två mål vilket leder till en stabil 3-0 seger för de gula och svarta.

I den tredje omgången är det dags för det alla har väntat på. Inför fullsatta läktare är det dags för matchen mellan
Mullsjö och Sandhem.
Och om

I och med två vinster och en oavgjord hamnar Mullsjö på en första plats i grupp A och får möta Norrahammar i semifinal.


<b>Övriga resultat</b>

<b>Grupp A</b>

Mullsjö: 7 poäng, +7 målskillnad
Sandhem: 5, +1
Månsarp 2: 3, +1
Råslätt: 0, -5

<b>Grupp B</b>
